### ISSUE TITLE
Starts Warpstudio

### ISSUE THREAD

**Issue by miton18** [senx/warp10-plugin-warpstudio#2]
Hi !
I can't see how to start WarpStudio without a Warp10 instance ?

**Comment by Giwi** [comment]
Hi, you can't it's a Warp 10 plugin.

**Comment by miton18** [comment]
it's an UI but you can't run it without a full Warp10 instance ?

**Comment by Giwi** [comment]
It's a Warp 10 plugin for now. It could become a standalone UI later, but for now, it needs a Warp 10 instance.

**Comment by miton18** [comment]
thx @Giwi, so we will wait to move from Quantum

**Comment by Giwi** [comment]
Sorry for that, I was totally focused on WarpStudio-*Plugin* wich, of course, cannot run outside Warp 10.
But, you can try https://bintray.com/senx/generic/warpstudio#files/io%2Fwarp10%2Fwarp10-warpstudio-server%2Fv1.0.30 
java -jar warp10-warpstudio-server.jar < optional properties file >

Properties : 
- warpstudio.port = 8082
- warpstudio.host = 127.0.0.1
- warpstudio.ssl.host
- warpstudio.ssl.port
- warpstudio.ssl.tcp.backlog
- warpstudio.ssl.acceptors = 2
- warpstudio.ssl.selectors = 4
- warpstudio.ssl.keystore.path
- warpstudio.ssl.keystore.password
- warpstudio.ssl.cert.alias
- warpstudio.ssl.keymanager.password
- warpstudio.ssl.idle.timeout


In fact, it works like Quantum. 

Sorry again. Best regards.
